# Upptime configuration
# Docs: https://upptime.js.org/docs/configuration

# Repository settings
owner: 17labs-ai          # Your GitHub org/user
repo: status              # Your Upptime repository name

# Monitoring targets
sites:
  - name: Dealya — Web
    url: https://deal-ya.com
    maxResponseTime: 8000

  - name: Flashcards — Web
    url: https://flashcards.17labs.ai
    maxResponseTime: 8000

  - name: Flashcards — API (Health)
    url: https://mcp-flashcards.17labs.ai/health
    maxResponseTime: 8000

# Status website
status-website:
  cname: status.17labs.ai
  # baseUrl: /status   # Use instead of cname if not on a custom domain

  name: 17labs Service Status

  # Logo not available yet
  # logoUrl: https://17labs.ai/logo.svg
  # favicon: https://17labs.ai/favicon.ico

  introTitle: "Service Status"
  introMessage: >
    This page provides real-time availability and incident history for 17labs services.
    If you are experiencing an issue not listed here, please contact our support team.

  navbar:
    - title: Status
      href: /

    # - title: Main Site
    #   href: https://17labs.ai

    - title: Support
      href: mailto:support@17labs.ai

    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  theme: dark
